---
- name: Install and configure JBoss EAP 8 on RHEL 9
  hosts: jboss_servers
  become: true

  vars:
    jboss_home: /opt/jboss
    jboss_user: jboss
    jboss_group: jboss
    jboss_version: 8.1
    jboss_zip: jboss-eap-8.1.0.zip
    mgmt_user: adminadmin
    mgmt_password: 'MyStrongPassword123!'
    mgmt_groups: ManagementRealm

  tasks:

  - name: Ensure required packages are installed
    dnf:
      name:
        - java-17-openjdk
        - unzip
      state: present

  - name: Create jboss user and group
    user:
      name: "{{ jboss_user }}"
      group: "{{ jboss_group }}"
      shell: /bin/bash
      create_home: yes

  - name: Create JBoss home directory
    file:
      path: "{{ jboss_home }}"
      state: directory
      owner: "{{ jboss_user }}"
      group: "{{ jboss_group }}"
      mode: 0755

  - name: Copy JBoss zip to server
    copy:
      src: "{{ jboss_zip }}"
      dest: "{{ jboss_home }}/"
      owner: "{{ jboss_user }}"
      group: "{{ jboss_group }}"
      mode: 0644

  - name: Unzip JBoss
    unarchive:
      src: "{{ jboss_home }}/{{ jboss_zip }}"
      dest: "{{ jboss_home }}"
      remote_src: yes
      owner: "{{ jboss_user }}"
      group: "{{ jboss_group }}"

  - name: Add management user
    command: >
      {{ jboss_home }}/jboss-eap-{{ jboss_version }}/bin/add-user.sh
      -a
      -u {{ mgmt_user }}
      -p {{ mgmt_password }}
      -g {{ mgmt_groups }}
    args:
      creates: "{{ jboss_home }}/jboss-eap-{{ jboss_version }}/standalone/configuration/mgmt-users.properties"

  - name: Configure firewall for 8080 and 9990
    firewalld:
      port: "{{ item }}/tcp"
      permanent: true
      state: enabled
      immediate: yes
    loop:
      - 8080
      - 9990

  - name: Create systemd service for JBoss
    copy:
      dest: /etc/systemd/system/jboss.service
      content: |
        [Unit]
        Description=JBoss EAP 8
        After=network.target

        [Service]
        User={{ jboss_user }}
        Group={{ jboss_group }}
        ExecStart={{ jboss_home }}/jboss-eap-{{ jboss_version }}/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
        ExecStop={{ jboss_home }}/jboss-eap-{{ jboss_version }}/bin/jboss-cli.sh --connect command=:shutdown
        Restart=on-failure
        LimitNOFILE=102642

        [Install]
        WantedBy=multi-user.target
    notify:
      - Reload systemd

  - name: Enable and start JBoss
    systemd:
      name: jboss
      enabled: yes
      state: started

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
