---
- name: Install and configure JBoss EAP 8 on RHEL 9
  hosts: jboss_servers
  become: true
  vars:
    jboss_home: /opt/jboss
    jboss_user: jboss
    jboss_group: jboss
    jboss_backup_tar: jboss.tar.gz
    # Remote server details for SCP
    remote_backup_server: 10.209.7.232
    remote_backup_path: /home/jboss/jboss.tar.gz
    remote_backup_user: jboss  # SSH user for the remote server
    # Configuration for existing user password update
    existing_user: jbosseap
    existing_user_new_password: 'NewSecurePassword456!'
    mgmt_groups: ManagementRealm
    
  tasks:
    - name: Ensure required packages are installed
      dnf:
        name:
          - java-21-openjdk
          - tar
          - rsync
        state: present

    - name: Create jboss group
      group:
        name: "{{ jboss_group }}"
        state: present

    - name: Create jboss user
      user:
        name: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        shell: /bin/bash
        create_home: yes

    - name: Stop JBoss service if running
      systemd:
        name: jboss
        state: stopped
      ignore_errors: yes

    - name: Create temporary directory for backup
      file:
        path: /tmp/jboss_restore
        state: directory
        mode: 0755

    - name: Copy JBoss backup from remote server via SCP
      command: >
        scp -o StrictHostKeyChecking=no 
        {{ remote_backup_user }}@{{ remote_backup_server }}:{{ remote_backup_path }}
        /tmp/jboss_restore/{{ jboss_backup_tar }}
      register: scp_result
      changed_when: scp_result.rc == 0
      failed_when: scp_result.rc != 0

    - name: Verify backup file was copied
      stat:
        path: "/tmp/jboss_restore/{{ jboss_backup_tar }}"
      register: backup_file
      failed_when: not backup_file.stat.exists

    - name: Display backup file size
      debug:
        msg: "Backup file size: {{ (backup_file.stat.size / 1024 / 1024) | round(2) }} MB"

    - name: Remove existing JBoss installation
      file:
        path: "{{ jboss_home }}"
        state: absent

    - name: Create JBoss home directory
      file:
        path: "{{ jboss_home }}"
        state: directory
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        mode: 0755

    - name: Extract JBoss backup to /opt
      unarchive:
        src: "/tmp/jboss_restore/{{ jboss_backup_tar }}"
        dest: /opt
        remote_src: yes
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"

    - name: Set correct ownership for all JBoss files
      file:
        path: "{{ jboss_home }}"
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        recurse: yes

    - name: Clean up backup file
      file:
        path: /tmp/jboss_restore
        state: absent

    - name: Check if management users file exists
      stat:
        path: "{{ jboss_home }}/standalone/configuration/mgmt-users.properties"
      register: mgmt_users_file

    - name: Verify add-user.sh script exists
      stat:
        path: "{{ jboss_home }}/bin/add-user.sh"
      register: add_user_script

    - name: Update password for existing user
      block:
        - name: Set executable permission on add-user.sh
          file:
            path: "{{ jboss_home }}/bin/add-user.sh"
            mode: 0755

        - name: Update user password
          shell: |
            {{ jboss_home }}/bin/add-user.sh -a \
            -u {{ existing_user }} \
            -p {{ existing_user_new_password }} \
            -g {{ mgmt_groups }} \
            --silent
          become_user: "{{ jboss_user }}"
          register: user_update
