---
- name: Install and configure JBoss EAP 8 on RHEL 9
  hosts: jboss_servers
  become: true
  vars:
    jboss_home: /opt/jboss
    jboss_user: jboss
    jboss_group: jboss
    jboss_version: 8.1
    jboss_zip: jboss-eap-8.1.0.zip
    jboss_backup_tar: jboss.tar.gz  # Your backup file
    restore_from_backup: false  # Set to true when restoring
    mgmt_user: adminadmin
    mgmt_password: 'MyStrongPassword123!'
    mgmt_groups: ManagementRealm
    # Configuration for existing user password update
    existing_user: jbosseap
    existing_user_new_password: 'NewSecurePassword456!'
    
  tasks:
    - name: Ensure required packages are installed
      dnf:
        name:
          - java-21-openjdk
          - unzip
          - tar
        state: present

    - name: Create jboss user and group
      user:
        name: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        shell: /bin/bash
        create_home: yes

    - name: Create JBoss home directory
      file:
        path: "{{ jboss_home }}"
        state: directory
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        mode: 0755

    # Backup restoration block
    - name: Restore from backup (if enabled)
      block:
        - name: Extract backup to JBoss home
          unarchive:
            src: "/tmp/{{ jboss_backup_tar }}"
            dest: /opt 
            remote_src: yes
            owner: "{{ jboss_user }}"
            group: "{{ jboss_group }}"

        - name: Clean up backup file
          file:
            path: "/tmp/{{ jboss_backup_tar }}"
            state: absent
      when: restore_from_backup | bool

    # Update existing user password (works for both scenarios)
    - name: Check if existing user needs password update
      stat:
        path: "{{ jboss_home }}/standalone/configuration/mgmt-users.properties"
      register: mgmt_users_file

    - name: Update password for existing user
      block:
        - name: Remove existing user entry
          command: >
            {{ jboss_home }}/bin/add-user.sh
            -u {{ existing_user }}
            -p {{ existing_user_new_password }}
            -g {{ mgmt_groups }}
          become_user: "{{ jboss_user }}"
          register: user_update
          failed_when: false

        - name: Display user update result
          debug:
            msg: "User {{ existing_user }} password has been updated"
          when: user_update.rc == 0
      when: 
        - mgmt_users_file.stat.exists
        - existing_user is defined
        - existing_user_new_password is defined

    - name: Set correct ownership for all JBoss files
      file:
        path: "{{ jboss_home }}"
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        recurse: yes

    - name: Configure firewall for 8080 and 9990
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - 8080
        - 9990

    - name: Create systemd service for JBoss
      copy:
        dest: /etc/systemd/system/jboss.service
        content: |
          [Unit]
          Description=JBoss EAP 8
          After=network.target

          [Service]
          User={{ jboss_user }}
          Group={{ jboss_group }}
          ExecStart={{ jboss_home }}/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
          ExecStop={{ jboss_home }}/bin/jboss-cli.sh --connect command=:shutdown
          Restart=on-failure
          RestartSec=10
          LimitNOFILE=102642

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

    - name: Enable and start JBoss
      systemd:
        name: jboss
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
